// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHHhxee9lZ44vRRey5lHejPrPit9i4LwQ',
    appId: '1:52189177510:web:6e82c53e660dbd5de03667',
    messagingSenderId: '52189177510',
    projectId: 'studyverse-8dd49',
    authDomain: 'studyverse-8dd49.firebaseapp.com',
    storageBucket: 'studyverse-8dd49.firebasestorage.app',
    measurementId: 'G-GQTV7G1YNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV6oUfh9hQz7-8o2gmfMt0Fxg96lUJmg4',
    appId: '1:52189177510:android:a307652a2e28609fe03667',
    messagingSenderId: '52189177510',
    projectId: 'studyverse-8dd49',
    storageBucket: 'studyverse-8dd49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzCZB_bdcVX_97z2KOiKxAWQZhxKPm24Y',
    appId: '1:52189177510:ios:64e5a07e4a0d86dee03667',
    messagingSenderId: '52189177510',
    projectId: 'studyverse-8dd49',
    storageBucket: 'studyverse-8dd49.firebasestorage.app',
    iosClientId:
        '52189177510-46759re0n2u4ccaie3fvs3vlp7u47267.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzCZB_bdcVX_97z2KOiKxAWQZhxKPm24Y',
    appId: '1:52189177510:ios:64e5a07e4a0d86dee03667',
    messagingSenderId: '52189177510',
    projectId: 'studyverse-8dd49',
    storageBucket: 'studyverse-8dd49.firebasestorage.app',
    iosClientId:
        '52189177510-46759re0n2u4ccaie3fvs3vlp7u47267.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHHhxee9lZ44vRRey5lHejPrPit9i4LwQ',
    appId: '1:52189177510:web:2c9d76628b177aa0e03667',
    messagingSenderId: '52189177510',
    projectId: 'studyverse-8dd49',
    authDomain: 'studyverse-8dd49.firebaseapp.com',
    storageBucket: 'studyverse-8dd49.firebasestorage.app',
    measurementId: 'G-SW916VCGBC',
  );
}
